server:
  port: 1029
  
spring:
  application:
    name: gnz48-zzt-yyh
  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.jdbc.Driver
#Mac
#    url: jdbc:mysql://localhost:3306/zztyyh?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
#    username: root
#    password: '0112'
#服务器(本机)
    url: jdbc:mysql://172.16.0.6:3306/zztyyh?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: zztyyh
    password: zztyyh1029
  jpa:
    database: mysql
    hibernate.ddl-auto: none
    show-sql: false
#    hibernate.ddl-auto: update
#    show-sql: true
  thymeleaf:
    #指定资源位置
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    #禁止浏览器缓存
    cache: false
    content-type: text/html; charset=utf-8
  #邮件配置
  mail:
    host: smtp.qq.com
    username: ${username}
    password: ${password}
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #上传文件配置
  http:
    multipart:
      max-request-size: 15MB
  #工作流配置
  activiti:
    database-schema-update: drop-create
    history-level: full
    check-process-definitions: false

#上传文件的外部静态根目录
web:
  upload-path: file:${path}
  
#MyBatis配置
mybatis:
  type-aliases-package: com.gnz48.zzt.dao
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    default-executor-type: simple

#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  
#口袋48配置
koudai48:
  username: ${username}
  password: ${password}